apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: helloworld-rubyapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - poornima-dev-app.apps.live-1.cloud-platform.service.justice.gov.uk
  - hosts:
    - staging.dev-pk.service.justice.gov.uk
    secretName: myruby-app-cert-secret
  rules:
  - host: poornima-dev-app.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: rubyapp-service
          servicePort: 4567
  - host: staging.dev-pk.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: rubyapp-service
          servicePort: 4567