apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: helloworld-rubyapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/set-identifier: poornima-demo-live-1
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  tls:
  - hosts:
    - poornima-demo-app.apps.live-1.cloud-platform.service.justice.gov.uk
  - hosts:
    - demo.dev-pk.service.justice.gov.uk
    secretName: myruby-app-cert-secret
  rules:
  - host: poornima-demo-app.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: rubyapp-service
          servicePort: 4567
  - host: demo.dev-pk.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: rubyapp-service
          servicePort: 4567
